[workspace]
resolver = "2"

members = [
    "examples/asset-id",
    "examples/predicate-root",
    "examples/simple-logs",
    "examples/stream-logs",
    "hyperfuel-client",
    "hyperfuel-format",
    "hyperfuel-net-types",
    "hyperfuel-schema",
]
