[package]
name = "hyperfuel-schema"
version = "0.0.3"
edition = "2021"
description = "schema utilities for hyperfuel"
license = "MIT"

[dependencies]
anyhow = "1"
arrow2 = { version = "0.18", default_features = false, features = [
    "compute_concatenate",
] }
