name: Publish to crates.io

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    inputs:
      crate_name:
        description: "The crate name to publish"
        required: true
        type: choice
        options:
          - hyperfuel-format
          - hyperfuel-schema
          - hyperfuel-net-types
          - hyperfuel-client

run-name: "Publish ${{ inputs.crate_name }} to crates.io"

jobs:
  publish_crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y capnproto libcapnp-dev

      - name: Authenticate with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@v1

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish -p ${{ inputs.crate_name }}
